from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

try:
    import numpy as np
    import pandas as pd
except Exception:  # pragma: no cover
    np = None
    pd = None


def _resolve_input_path(dataset_path: str | Path | None = None) -> Path:
    """
    Resolve dataset path with fallback names.

    Priority:
    1) Explicit dataset_path (if provided)
    2) aws_clean.csv (user requested name)
    3) aqs_clean.csv (name generated by notebook)
    """
    if dataset_path is not None:
        path = Path(dataset_path)
        if path.exists():
            return path
        raise FileNotFoundError(f"No se encontro el archivo indicado: {path}")

    candidates = [Path("aws_clean.csv"), Path("aqs_clean.csv")]
    for candidate in candidates:
        if candidate.exists():
            return candidate

    tried = ", ".join(str(p) for p in candidates)
    raise FileNotFoundError(
        f"No se encontro el dataset. Intente con uno de estos nombres: {tried}"
    )


def analyze_aqs_clean(
    dataset_path: str | Path | None = None,
    max_numeric_cols: int = 15,
    top_n_categories: int = 10,
) -> dict[str, Any]:
    """
    Basic EDA for AQS-EPA cleaned dataset (aws_clean.csv / aqs_clean.csv).

    Returns:
        A dictionary with key metrics that can be consumed programmatically.
    """
    path = _resolve_input_path(dataset_path)
    if pd is not None and np is not None:
        return _analyze_with_pandas(path, max_numeric_cols, top_n_categories)
    return _analyze_with_stdlib(path, top_n_categories)


def _analyze_with_pandas(
    path: Path,
    max_numeric_cols: int,
    top_n_categories: int,
) -> dict[str, Any]:
    df = pd.read_csv(path)

    report: dict[str, Any] = {}
    report["file"] = str(path.resolve())
    report["shape"] = {"rows": int(df.shape[0]), "cols": int(df.shape[1])}

    report["column_types"] = {
        "numeric": df.select_dtypes(include=[np.number]).columns.tolist(),
        "categorical_or_text": df.select_dtypes(exclude=[np.number]).columns.tolist(),
    }

    missing = df.isna().sum().sort_values(ascending=False)
    report["missing_values_top"] = (
        missing[missing > 0].head(20).astype(int).to_dict()
        if missing.sum() > 0
        else {}
    )
    report["duplicates"] = {
        "full_row_duplicates": int(df.duplicated().sum()),
    }

    if {"State Code", "County Code", "Site Num", "Parameter Code", "Year"}.issubset(df.columns):
        station_year_dup = df.duplicated(
            subset=["State Code", "County Code", "Site Num", "Parameter Code", "Year"]
        ).sum()
        report["duplicates"]["monitor_year_key_duplicates"] = int(station_year_dup)

    if "Year" in df.columns:
        report["year_coverage"] = {
            "min_year": int(df["Year"].min()),
            "max_year": int(df["Year"].max()),
            "n_unique_years": int(df["Year"].nunique()),
        }

    if "pollutant" in df.columns:
        poll = df["pollutant"].value_counts(dropna=False)
        report["pollutant_distribution"] = poll.to_dict()

    # Numeric profile
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    numeric_summary: dict[str, Any] = {}
    if numeric_cols:
        selected_numeric = numeric_cols[:max_numeric_cols]
        desc = df[selected_numeric].describe().T
        numeric_summary = {
            col: {
                "count": float(desc.loc[col, "count"]),
                "mean": float(desc.loc[col, "mean"]),
                "std": float(desc.loc[col, "std"]) if pd.notna(desc.loc[col, "std"]) else None,
                "min": float(desc.loc[col, "min"]),
                "p50": float(desc.loc[col, "50%"]),
                "max": float(desc.loc[col, "max"]),
            }
            for col in selected_numeric
        }
    report["numeric_summary"] = numeric_summary

    # Category profile
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
    category_summary: dict[str, Any] = {}
    for col in cat_cols[:10]:
        vc = df[col].value_counts(dropna=False).head(top_n_categories)
        category_summary[col] = {str(k): int(v) for k, v in vc.items()}
    report["categorical_top_values"] = category_summary

    # Correlations in concentration metrics (if present)
    concentration_cols = [
        "Arithmetic Mean",
        "1st Max Value",
        "99th Percentile",
        "50th Percentile",
    ]
    present = [c for c in concentration_cols if c in df.columns]
    if len(present) >= 2:
        corr = df[present].corr(numeric_only=True).round(4)
        report["concentration_correlations"] = corr.to_dict()
    else:
        report["concentration_correlations"] = {}

    # Pretty print quick summary
    print("=" * 72)
    print("Analisis basico del dataset AQS-EPA limpio")
    print("=" * 72)
    print(f"Archivo: {report['file']}")
    print(f"Filas: {report['shape']['rows']:,} | Columnas: {report['shape']['cols']}")
    if "year_coverage" in report:
        yc = report["year_coverage"]
        print(
            f"Rango de anos: {yc['min_year']} - {yc['max_year']} "
            f"({yc['n_unique_years']} anos)"
        )
    if report["missing_values_top"]:
        print("\nTop columnas con nulos:")
        for k, v in report["missing_values_top"].items():
            print(f"  - {k}: {v:,}")
    else:
        print("\nNo se detectaron nulos.")

    if "pollutant_distribution" in report:
        print("\nDistribucion por contaminante:")
        for k, v in report["pollutant_distribution"].items():
            print(f"  - {k}: {v:,}")

    print("\nDuplicados:")
    for k, v in report["duplicates"].items():
        print(f"  - {k}: {v:,}")

    print("=" * 72)
    return report


def _analyze_with_stdlib(path: Path, top_n_categories: int) -> dict[str, Any]:
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        columns = reader.fieldnames or []
        if not columns:
            raise ValueError("El CSV no tiene cabecera valida.")

        row_count = 0
        missing_counts = {c: 0 for c in columns}
        pollutant_counts: dict[str, int] = {}
        year_min = None
        year_max = None
        years_seen = set()
        monitor_key_seen = set()
        monitor_key_dups = 0

        # Numeric metrics (running stats by column)
        numeric_stats = {
            c: {"count": 0, "mean": 0.0, "m2": 0.0, "min": None, "max": None}
            for c in columns
        }
        cat_counts = {c: {} for c in columns}

        for row in reader:
            row_count += 1
            for c in columns:
                value = row.get(c, "")
                if value is None or value == "":
                    missing_counts[c] += 1
                    continue

                # Category counts
                if len(cat_counts[c]) <= top_n_categories * 15:
                    cat_counts[c][value] = cat_counts[c].get(value, 0) + 1

                # Numeric running stats
                try:
                    x = float(value)
                except Exception:
                    continue
                st = numeric_stats[c]
                st["count"] += 1
                if st["min"] is None or x < st["min"]:
                    st["min"] = x
                if st["max"] is None or x > st["max"]:
                    st["max"] = x
                delta = x - st["mean"]
                st["mean"] += delta / st["count"]
                delta2 = x - st["mean"]
                st["m2"] += delta * delta2

            pollutant = row.get("pollutant")
            if pollutant:
                pollutant_counts[pollutant] = pollutant_counts.get(pollutant, 0) + 1

            year_value = row.get("Year")
            if year_value:
                try:
                    y = int(float(year_value))
                    years_seen.add(y)
                    year_min = y if year_min is None else min(year_min, y)
                    year_max = y if year_max is None else max(year_max, y)
                except Exception:
                    pass

            key_cols = ("State Code", "County Code", "Site Num", "Parameter Code", "Year")
            if all(k in row and row[k] not in (None, "") for k in key_cols):
                key = tuple(row[k] for k in key_cols)
                if key in monitor_key_seen:
                    monitor_key_dups += 1
                else:
                    monitor_key_seen.add(key)

    missing_nonzero = {k: v for k, v in sorted(missing_counts.items(), key=lambda x: x[1], reverse=True) if v > 0}
    missing_nonzero = dict(list(missing_nonzero.items())[:20])

    numeric_summary = {}
    for c, st in numeric_stats.items():
        if st["count"] == 0:
            continue
        variance = (st["m2"] / (st["count"] - 1)) if st["count"] > 1 else 0.0
        numeric_summary[c] = {
            "count": float(st["count"]),
            "mean": float(st["mean"]),
            "std": float(variance ** 0.5),
            "min": float(st["min"]) if st["min"] is not None else None,
            "max": float(st["max"]) if st["max"] is not None else None,
        }

    # Keep likely numeric columns first
    numeric_summary = dict(
        sorted(numeric_summary.items(), key=lambda x: (-x[1]["count"], x[0]))[:15]
    )

    category_summary = {}
    non_numeric_cols = [c for c in columns if c not in numeric_summary]
    for c in non_numeric_cols[:10]:
        sorted_top = sorted(cat_counts[c].items(), key=lambda x: x[1], reverse=True)[:top_n_categories]
        category_summary[c] = {k: int(v) for k, v in sorted_top}

    report: dict[str, Any] = {
        "file": str(path.resolve()),
        "shape": {"rows": int(row_count), "cols": int(len(columns))},
        "column_types": {
            "numeric": list(numeric_summary.keys()),
            "categorical_or_text": non_numeric_cols,
        },
        "missing_values_top": missing_nonzero,
        "duplicates": {"monitor_year_key_duplicates": int(monitor_key_dups)},
        "numeric_summary": numeric_summary,
        "categorical_top_values": category_summary,
        "concentration_correlations": {},
    }

    if years_seen:
        report["year_coverage"] = {
            "min_year": int(year_min),
            "max_year": int(year_max),
            "n_unique_years": int(len(years_seen)),
        }
    if pollutant_counts:
        report["pollutant_distribution"] = pollutant_counts

    print("=" * 72)
    print("Analisis basico del dataset AQS-EPA limpio (modo stdlib)")
    print("=" * 72)
    print(f"Archivo: {report['file']}")
    print(f"Filas: {report['shape']['rows']:,} | Columnas: {report['shape']['cols']}")
    if "year_coverage" in report:
        yc = report["year_coverage"]
        print(
            f"Rango de anos: {yc['min_year']} - {yc['max_year']} "
            f"({yc['n_unique_years']} anos)"
        )
    if report["missing_values_top"]:
        print("\nTop columnas con nulos:")
        for k, v in report["missing_values_top"].items():
            print(f"  - {k}: {v:,}")
    else:
        print("\nNo se detectaron nulos.")
    if "pollutant_distribution" in report:
        print("\nDistribucion por contaminante:")
        for k, v in report["pollutant_distribution"].items():
            print(f"  - {k}: {v:,}")
    print("\nDuplicados:")
    for k, v in report["duplicates"].items():
        print(f"  - {k}: {v:,}")
    print("=" * 72)
    return report


if __name__ == "__main__":
    analyze_aqs_clean()
